swagger: '2.0'
info:
  version: 0.4.0
  title: GA4GH Beacon API specification
  description: >-
    A Beacon is a web service for genetic data sharing that can be queried for information about specific alleles.
host: egatest.crg.eu
basePath: /requesterportal/v1/beacon
schemes:
  - https
  - http
paths:
  /:
    $ref: '#/beacon.yaml/paths/~1'
  /query:
    $ref: '#/beacon.yaml/paths/~1query'

# definitions:
#   $ref: 'https://raw.githubusercontent.com/sdelatorrep/beacon-team/open_api/src/main/definitions.yaml'